package mat

const (
	// model is base64 representation of protocol buffer TF model.
	// this go file was auto-generated using following command:
	//      go get github.com/sdeoras/tensorflow/cmd/mo
	//      mo u -h
	modelPB = "" +
		"CjUKB3ZlcnNpb24SBUNvbnN0KhYKBXZhbHVlEg1CCwgHEgBCBTAuMS4wKgsKBWR0eXBlEgIwBwowCgVi" +
		"dWZmMRILUGxhY2Vob2xkZXIqCwoFZHR5cGUSAjACKg0KBXNoYXBlEgQ6AhgBCjEKBnNoYXBlMRILUGxh" +
		"Y2Vob2xkZXIqCwoFZHR5cGUSAjAJKg0KBXNoYXBlEgQ6AhgBCjAKBWJ1ZmYyEgtQbGFjZWhvbGRlcioL" +
		"CgVkdHlwZRICMAIqDQoFc2hhcGUSBDoCGAEKMQoGc2hhcGUyEgtQbGFjZWhvbGRlcioLCgVkdHlwZRIC" +
		"MAkqDQoFc2hhcGUSBDoCGAEKNQoKc2hhcGVCZWdpbhILUGxhY2Vob2xkZXIqCwoFZHR5cGUSAjAJKg0K" +
		"BXNoYXBlEgQ6AhgBCjQKCXNoYXBlU2l6ZRILUGxhY2Vob2xkZXIqCwoFZHR5cGUSAjAJKg0KBXNoYXBl" +
		"EgQ6AhgBCjgKB1Jlc2hhcGUSB1Jlc2hhcGUaBWJ1ZmYxGgZzaGFwZTEqBwoBVBICMAIqDAoGVHNoYXBl" +
		"EgIwCQo/Cg1NYXRyaXhJbnZlcnNlEg1NYXRyaXhJbnZlcnNlGgdSZXNoYXBlKgcKAVQSAjACKg0KB2Fk" +
		"am9pbnQSAigACkAKCWludi9zaGFwZRIFQ29uc3QqHwoFdmFsdWUSFkIUCAMSBBICCAE6Cv//////////" +
		"/wEqCwoFZHR5cGUSAjADCj8KA2ludhIHUmVzaGFwZRoNTWF0cml4SW52ZXJzZRoJaW52L3NoYXBlKgcK" +
		"AVQSAjACKgwKBlRzaGFwZRICMAMKOgoJUmVzaGFwZV8xEgdSZXNoYXBlGgVidWZmMRoGc2hhcGUxKgcK" +
		"AVQSAjACKgwKBlRzaGFwZRICMAkKMQoCUXISAlFyGglSZXNoYXBlXzEqBwoBVBICMAIqEwoNZnVsbF9t" +
		"YXRyaWNlcxICKAEKRgoPUmVzaGFwZV8yL3NoYXBlEgVDb25zdCofCgV2YWx1ZRIWQhQIAxIEEgIIAToK" +
		"////////////ASoLCgVkdHlwZRICMAMKQAoJUmVzaGFwZV8yEgdSZXNoYXBlGgJRchoPUmVzaGFwZV8y" +
		"L3NoYXBlKgcKAVQSAjACKgwKBlRzaGFwZRICMAMKRgoPUmVzaGFwZV8zL3NoYXBlEgVDb25zdCofCgV2" +
		"YWx1ZRIWQhQIAxIEEgIIAToK////////////ASoLCgVkdHlwZRICMAMKQgoJUmVzaGFwZV8zEgdSZXNo" +
		"YXBlGgRRcjoxGg9SZXNoYXBlXzMvc2hhcGUqBwoBVBICMAIqDAoGVHNoYXBlEgIwAwoqCgpxcmRlY29t" +
		"cF9xEghJZGVudGl0eRoJUmVzaGFwZV8yKgcKAVQSAjACCioKCnFyZGVjb21wX3ISCElkZW50aXR5GglS" +
		"ZXNoYXBlXzMqBwoBVBICMAIKSgoTemVyb3MvUmVzaGFwZS9zaGFwZRIFQ29uc3QqHwoFdmFsdWUSFkIU" +
		"CAMSBBICCAE6Cv///////////wEqCwoFZHR5cGUSAjADCkwKDXplcm9zL1Jlc2hhcGUSB1Jlc2hhcGUa" +
		"BnNoYXBlMRoTemVyb3MvUmVzaGFwZS9zaGFwZSoHCgFUEgIwCSoMCgZUc2hhcGUSAjADCjwKC3plcm9z" +
		"L0NvbnN0EgVDb25zdCoLCgVkdHlwZRICMAIqGQoFdmFsdWUSEEIOCAISADIIAAAAAAAAAAAKRAoFemVy" +
		"b3MSBEZpbGwaDXplcm9zL1Jlc2hhcGUaC3plcm9zL0NvbnN0KgcKAVQSAjACKhAKCmluZGV4X3R5cGUS" +
		"AjAJCkQKDXplcm9zXzEvc2hhcGUSBUNvbnN0KgsKBWR0eXBlEgIwAyofCgV2YWx1ZRIWQhQIAxIEEgII" +
		"AToK////////////AQo/Cgd6ZXJvc18xEgdSZXNoYXBlGgV6ZXJvcxoNemVyb3NfMS9zaGFwZSoHCgFU" +
		"EgIwAioMCgZUc2hhcGUSAjADCkkKEm9uZXMvUmVzaGFwZS9zaGFwZRIFQ29uc3QqHwoFdmFsdWUSFkIU" +
		"CAMSBBICCAE6Cv///////////wEqCwoFZHR5cGUSAjADCkoKDG9uZXMvUmVzaGFwZRIHUmVzaGFwZRoG" +
		"c2hhcGUxGhJvbmVzL1Jlc2hhcGUvc2hhcGUqBwoBVBICMAkqDAoGVHNoYXBlEgIwAwo7CgpvbmVzL0Nv" +
		"bnN0EgVDb25zdCoZCgV2YWx1ZRIQQg4IAhIAMggAAAAAAADwPyoLCgVkdHlwZRICMAIKQQoEb25lcxIE" +
		"RmlsbBoMb25lcy9SZXNoYXBlGgpvbmVzL0NvbnN0KgcKAVQSAjACKhAKCmluZGV4X3R5cGUSAjAJCkMK" +
		"DG9uZXNfMS9zaGFwZRIFQ29uc3QqHwoFdmFsdWUSFkIUCAMSBBICCAE6Cv///////////wEqCwoFZHR5" +
		"cGUSAjADCjwKBm9uZXNfMRIHUmVzaGFwZRoEb25lcxoMb25lc18xL3NoYXBlKgcKAVQSAjACKgwKBlRz" +
		"aGFwZRICMAMKQwoScmFuZG9tX3VuaWZvcm0vbWluEgVDb25zdCoLCgVkdHlwZRICMAIqGQoFdmFsdWUS" +
		"EEIOCAISADIIAAAAAAAAAAAKQwoScmFuZG9tX3VuaWZvcm0vbWF4EgVDb25zdCoZCgV2YWx1ZRIQQg4I" +
		"AhIAMggAAAAAAADwPyoLCgVkdHlwZRICMAIKZAoccmFuZG9tX3VuaWZvcm0vUmFuZG9tVW5pZm9ybRIN" +
		"UmFuZG9tVW5pZm9ybRoGc2hhcGUxKgsKBWR0eXBlEgIwAioLCgVzZWVkMhICGAAqCgoEc2VlZBICGAAq" +
		"BwoBVBICMAkKSgoScmFuZG9tX3VuaWZvcm0vc3ViEgNTdWIaEnJhbmRvbV91bmlmb3JtL21heBoScmFu" +
		"ZG9tX3VuaWZvcm0vbWluKgcKAVQSAjACClQKEnJhbmRvbV91bmlmb3JtL211bBIDTXVsGhxyYW5kb21f" +
		"dW5pZm9ybS9SYW5kb21Vbmlmb3JtGhJyYW5kb21fdW5pZm9ybS9zdWIqBwoBVBICMAIKRgoOcmFuZG9t" +
		"X3VuaWZvcm0SA0FkZBoScmFuZG9tX3VuaWZvcm0vbXVsGhJyYW5kb21fdW5pZm9ybS9taW4qBwoBVBIC" +
		"MAIKQQoKcmFuZC9zaGFwZRIFQ29uc3QqHwoFdmFsdWUSFkIUCAMSBBICCAE6Cv///////////wEqCwoF" +
		"ZHR5cGUSAjADCkIKBHJhbmQSB1Jlc2hhcGUaDnJhbmRvbV91bmlmb3JtGgpyYW5kL3NoYXBlKgcKAVQS" +
		"AjACKgwKBlRzaGFwZRICMAMKQwoScmFuZG9tX25vcm1hbC9tZWFuEgVDb25zdCoZCgV2YWx1ZRIQQg4I" +
		"AhIAMggAAAAAAAAAACoLCgVkdHlwZRICMAIKRQoUcmFuZG9tX25vcm1hbC9zdGRkZXYSBUNvbnN0KhkK" +
		"BXZhbHVlEhBCDggCEgAyCAAAAAAAAPA/KgsKBWR0eXBlEgIwAgpxCiJyYW5kb21fbm9ybWFsL1JhbmRv" +
		"bVN0YW5kYXJkTm9ybWFsEhRSYW5kb21TdGFuZGFyZE5vcm1hbBoGc2hhcGUxKgoKBHNlZWQSAhgAKgcK" +
		"AVQSAjAJKgsKBWR0eXBlEgIwAioLCgVzZWVkMhICGAAKWwoRcmFuZG9tX25vcm1hbC9tdWwSA011bBoi" +
		"cmFuZG9tX25vcm1hbC9SYW5kb21TdGFuZGFyZE5vcm1hbBoUcmFuZG9tX25vcm1hbC9zdGRkZXYqBwoB" +
		"VBICMAIKRAoNcmFuZG9tX25vcm1hbBIDQWRkGhFyYW5kb21fbm9ybWFsL211bBoScmFuZG9tX25vcm1h" +
		"bC9tZWFuKgcKAVQSAjACCkIKC3JhbmRuL3NoYXBlEgVDb25zdCoLCgVkdHlwZRICMAMqHwoFdmFsdWUS" +
		"FkIUCAMSBBICCAE6Cv///////////wEKRAoFcmFuZG4SB1Jlc2hhcGUaDnJhbmRvbV91bmlmb3JtGgty" +
		"YW5kbi9zaGFwZSoHCgFUEgIwAioMCgZUc2hhcGUSAjADCjoKCVJlc2hhcGVfNBIHUmVzaGFwZRoFYnVm" +
		"ZjEaBnNoYXBlMSoHCgFUEgIwAioMCgZUc2hhcGUSAjAJCjoKCVJlc2hhcGVfNRIHUmVzaGFwZRoFYnVm" +
		"ZjIaBnNoYXBlMioHCgFUEgIwAioMCgZUc2hhcGUSAjAJCk4KBk1hdE11bBILQmF0Y2hNYXRNdWwaCVJl" +
		"c2hhcGVfNBoJUmVzaGFwZV81KgsKBWFkal94EgIoACoLCgVhZGpfeRICKAAqBwoBVBICMAIKMgoIbXVs" +
		"U2hhcGUSBVNoYXBlGgZNYXRNdWwqBwoBVBICMAIqDgoIb3V0X3R5cGUSAjAJCkAKCW11bC9zaGFwZRIF" +
		"Q29uc3QqHwoFdmFsdWUSFkIUCAMSBBICCAE6Cv///////////wEqCwoFZHR5cGUSAjADCjgKA211bBIH" +
		"UmVzaGFwZRoGTWF0TXVsGgltdWwvc2hhcGUqBwoBVBICMAIqDAoGVHNoYXBlEgIwAwo6CglSZXNoYXBl" +
		"XzYSB1Jlc2hhcGUaBWJ1ZmYxGgZzaGFwZTEqBwoBVBICMAIqDAoGVHNoYXBlEgIwCQpGCgVTbGljZRIF" +
		"U2xpY2UaCVJlc2hhcGVfNhoKc2hhcGVCZWdpbhoJc2hhcGVTaXplKgcKAVQSAjACKgsKBUluZGV4EgIw" +
		"CQouCgVTaGFwZRIFU2hhcGUaBVNsaWNlKgcKAVQSAjACKg4KCG91dF90eXBlEgIwCQooCgxzbGljZVNo" +
		"YXBlT3ASCElkZW50aXR5GgVTaGFwZSoHCgFUEgIwCQpGCg9SZXNoYXBlXzcvc2hhcGUSBUNvbnN0Kh8K" +
		"BXZhbHVlEhZCFAgDEgQSAggBOgr///////////8BKgsKBWR0eXBlEgIwAwpDCglSZXNoYXBlXzcSB1Jl" +
		"c2hhcGUaBVNsaWNlGg9SZXNoYXBlXzcvc2hhcGUqBwoBVBICMAIqDAoGVHNoYXBlEgIwAwonCgdzbGlj" +
		"ZU9wEghJZGVudGl0eRoJUmVzaGFwZV83KgcKAVQSAjACCjoKCVJlc2hhcGVfOBIHUmVzaGFwZRoFYnVm" +
		"ZjEaBnNoYXBlMSoHCgFUEgIwAioMCgZUc2hhcGUSAjAJCj4KCVJlc2hhcGVfORIHUmVzaGFwZRoJUmVz" +
		"aGFwZV84GgZzaGFwZTIqBwoBVBICMAIqDAoGVHNoYXBlEgIwCQpHChBSZXNoYXBlXzEwL3NoYXBlEgVD" +
		"b25zdCofCgV2YWx1ZRIWQhQIAxIEEgIIAToK////////////ASoLCgVkdHlwZRICMAMKSQoKUmVzaGFw" +
		"ZV8xMBIHUmVzaGFwZRoJUmVzaGFwZV85GhBSZXNoYXBlXzEwL3NoYXBlKgcKAVQSAjACKgwKBlRzaGFw" +
		"ZRICMAMKKgoJcmVzaGFwZU9wEghJZGVudGl0eRoKUmVzaGFwZV8xMCoHCgFUEgIwAgo7CgpSZXNoYXBl" +
		"XzExEgdSZXNoYXBlGgVidWZmMRoGc2hhcGUxKgcKAVQSAjACKgwKBlRzaGFwZRICMAkKOwoEVGlsZRIE" +
		"VGlsZRoKUmVzaGFwZV8xMRoGc2hhcGUyKgcKAVQSAjACKhAKClRtdWx0aXBsZXMSAjAJCi8KB1NoYXBl" +
		"XzESBVNoYXBlGgRUaWxlKgcKAVQSAjACKg4KCG91dF90eXBlEgIwCQopCgt0aWxlU2hhcGVPcBIISWRl" +
		"bnRpdHkaB1NoYXBlXzEqBwoBVBICMAkKRwoQUmVzaGFwZV8xMi9zaGFwZRIFQ29uc3QqHwoFdmFsdWUS" +
		"FkIUCAMSBBICCAE6Cv///////////wEqCwoFZHR5cGUSAjADCkQKClJlc2hhcGVfMTISB1Jlc2hhcGUa" +
		"BFRpbGUaEFJlc2hhcGVfMTIvc2hhcGUqBwoBVBICMAIqDAoGVHNoYXBlEgIwAwonCgZ0aWxlT3ASCElk" +
		"ZW50aXR5GgpSZXNoYXBlXzEyKgcKAVQSAjACIgIIGw=="
)
