# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comp.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ncomp.proto\x12\x05proto\"\xed\x01\n\nCheckpoint\x12/\n\x07weights\x18\x01 \x03(\x0b\x32\x1e.proto.Checkpoint.WeightsEntry\x12-\n\x06\x62iases\x18\x02 \x03(\x0b\x32\x1d.proto.Checkpoint.BiasesEntry\x1a?\n\x0cWeightsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.proto.Variable:\x02\x38\x01\x1a>\n\x0b\x42iasesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.proto.Variable:\x02\x38\x01\"&\n\x08Variable\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\x0c\n\x04size\x18\x02 \x03(\x03\x62\x06proto3')
)




_CHECKPOINT_WEIGHTSENTRY = _descriptor.Descriptor(
  name='WeightsEntry',
  full_name='proto.Checkpoint.WeightsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.Checkpoint.WeightsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Checkpoint.WeightsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=195,
)

_CHECKPOINT_BIASESENTRY = _descriptor.Descriptor(
  name='BiasesEntry',
  full_name='proto.Checkpoint.BiasesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.Checkpoint.BiasesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.Checkpoint.BiasesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=259,
)

_CHECKPOINT = _descriptor.Descriptor(
  name='Checkpoint',
  full_name='proto.Checkpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weights', full_name='proto.Checkpoint.weights', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='biases', full_name='proto.Checkpoint.biases', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CHECKPOINT_WEIGHTSENTRY, _CHECKPOINT_BIASESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=259,
)


_VARIABLE = _descriptor.Descriptor(
  name='Variable',
  full_name='proto.Variable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='proto.Variable.data', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='proto.Variable.size', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=299,
)

_CHECKPOINT_WEIGHTSENTRY.fields_by_name['value'].message_type = _VARIABLE
_CHECKPOINT_WEIGHTSENTRY.containing_type = _CHECKPOINT
_CHECKPOINT_BIASESENTRY.fields_by_name['value'].message_type = _VARIABLE
_CHECKPOINT_BIASESENTRY.containing_type = _CHECKPOINT
_CHECKPOINT.fields_by_name['weights'].message_type = _CHECKPOINT_WEIGHTSENTRY
_CHECKPOINT.fields_by_name['biases'].message_type = _CHECKPOINT_BIASESENTRY
DESCRIPTOR.message_types_by_name['Checkpoint'] = _CHECKPOINT
DESCRIPTOR.message_types_by_name['Variable'] = _VARIABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Checkpoint = _reflection.GeneratedProtocolMessageType('Checkpoint', (_message.Message,), dict(

  WeightsEntry = _reflection.GeneratedProtocolMessageType('WeightsEntry', (_message.Message,), dict(
    DESCRIPTOR = _CHECKPOINT_WEIGHTSENTRY,
    __module__ = 'comp_pb2'
    # @@protoc_insertion_point(class_scope:proto.Checkpoint.WeightsEntry)
    ))
  ,

  BiasesEntry = _reflection.GeneratedProtocolMessageType('BiasesEntry', (_message.Message,), dict(
    DESCRIPTOR = _CHECKPOINT_BIASESENTRY,
    __module__ = 'comp_pb2'
    # @@protoc_insertion_point(class_scope:proto.Checkpoint.BiasesEntry)
    ))
  ,
  DESCRIPTOR = _CHECKPOINT,
  __module__ = 'comp_pb2'
  # @@protoc_insertion_point(class_scope:proto.Checkpoint)
  ))
_sym_db.RegisterMessage(Checkpoint)
_sym_db.RegisterMessage(Checkpoint.WeightsEntry)
_sym_db.RegisterMessage(Checkpoint.BiasesEntry)

Variable = _reflection.GeneratedProtocolMessageType('Variable', (_message.Message,), dict(
  DESCRIPTOR = _VARIABLE,
  __module__ = 'comp_pb2'
  # @@protoc_insertion_point(class_scope:proto.Variable)
  ))
_sym_db.RegisterMessage(Variable)


_CHECKPOINT_WEIGHTSENTRY._options = None
_CHECKPOINT_BIASESENTRY._options = None
# @@protoc_insertion_point(module_scope)
